# Generated by Django 3.1.1 on 2020-09-21 12:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_question_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 21, 12, 10, 12, 251409, tzinfo=utc)),
        ),
    ]
